version: "3.1"

services:
  app:
    image: palash29/node-app:0.0.3
    ports:
      - "3100:3100"
    networks:
      - onet
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
    networks:
      - onet
    deploy:
      placement:
        constraints: [node.role == manager]

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - onet

networks:
  onet:
    driver: overlay

volumes:
  db-data:
