apiVersion: v1
kind: Pod
metadata:
    name: node-pod
    labels:
        app: web
spec:
    containers:
    - name: web-ctr
      image: palash29/node-app:0.0.2
      ports:
      - containerPort: 3100