apiVersion: v1
kind: Service
metadata:
  name: node-lb
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 3100
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  template: # Pod spec
    metadata:
      labels:
        app: web-app
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: node-app
        image: palash29/node-app:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/testdb